import UIKit

class OnboardingPageViewController: UIPageViewController {

    private var controllers: [UIViewController] = []
    private var currentIndex: Int = 0
    private let pageControl = UIPageControl()
    var selectedLevel: String?
    var selectedDomains: [String] = []
    var selectedInterests: [String] = []

    override func viewDidLoad() {
        super.viewDidLoad()
        setupControllers()
    }

    private func setupControllers() {
        let storyboard = UIStoryboard(name: "Onboarding", bundle: nil)

        // STEP 1 — Investment Level
        let step1 = storyboard.instantiateViewController(
            withIdentifier: "OnboardingContentViewController"
        ) as! OnboardingContentViewController

        step1.loadViewIfNeeded()
        step1.configure(
            with: OnboardingPage(
                title: "Select your investment experience level",
                options: [
                    (title: "Beginner", subtitle: "Just starting my financial journey"),
                    (title: "Intermediate", subtitle: "I have some experience"),
                    (title: "Advanced", subtitle: "I understand markets")
                ]
            )
        )

        step1.onOptionSelected = { [weak self] selected in
            self?.selectedLevel = selected
        }

        step1.onNextTapped = { [weak self] in
            self?.goToNextPage()
        }
        
        step1.onSkipTapped = { [weak self] in
            print("⏭️ User chose to skip onboarding. Navigating to Home safely...")
            self?.navigateToHome()
        }

        // STEP 2 — Interest Selection
        let step2 = storyboard.instantiateViewController(
            withIdentifier: "InterestCollectionViewController"
        ) as! InterestCollectionViewController

        step2.onFinishTapped = { [weak self] in
            if let indexPaths = step2.interestCollectionView.indexPathsForSelectedItems {
                self?.selectedInterests = indexPaths.map { preferences[$0.item].title }
            }
            self?.submitOnboardingToBackend()
        }

        step2.onBackTapped = { [weak self] in
            self?.goToPreviousPage()
        }

        controllers = [step1, step2]

        pageControl.numberOfPages = controllers.count
        pageControl.currentPage = 0
        pageControl.pageIndicatorTintColor = UIColor.systemGray4
        pageControl.currentPageIndicatorTintColor = UIColor.systemBlue // or any brand color
        pageControl.isUserInteractionEnabled = false 
        pageControl.translatesAutoresizingMaskIntoConstraints = false
        
        // Add to main view and pin to the bottom
        view.addSubview(pageControl)
        NSLayoutConstraint.activate([
            pageControl.centerYAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -70),            pageControl.centerXAnchor.constraint(equalTo: view.centerXAnchor)
        ])

        setViewControllers(
            [controllers[0]],
            direction: .forward,
            animated: false
        )
    }

    // MARK: - Navigation

    func goToNextPage() {
        guard currentIndex + 1 < controllers.count else {
            print("Onboarding finished")
            return
        }
        currentIndex += 1
        
        // 3a. Update the dot forwards!
        pageControl.currentPage = currentIndex 
        
        setViewControllers(
            [controllers[currentIndex]],
            direction: .forward,
            animated: true
        )
    }
    func goToPreviousPage() {
        guard currentIndex - 1 >= 0 else { return }
        currentIndex -= 1
        
        // 3b. Update the dot backwards!
        pageControl.currentPage = currentIndex 
        
        setViewControllers(
            [controllers[currentIndex]],
            direction: .reverse,
            animated: true
        )
    } 

    // MARK: - Submission (saves to DATABASE via API)

        // MARK: - Submission (saves to DATABASE via API)

    func submitOnboardingToBackend() {
        guard let token = UserDefaults.standard.string(forKey: "authToken") else {
            print("❌ No auth token found")
            return
        }

        // Use the main, strongly-typed APIService
        let api = APIService.shared
        let dispatchGroup = DispatchGroup()

        // 1) Save level using the API level enum implicitly generated by the string
        if let levelString = selectedLevel {
            dispatchGroup.enter()
            // The APIService Compatibility Helper will map the string for us
            api.saveLevel(levelString, token: token) { success in
                print("Level saved to DB: \(success)")
                dispatchGroup.leave()
            }
        }

        // 2) Fetch strongly-typed interests, match by name, then POST each
        dispatchGroup.enter()
        api.fetchAvailableInterests(type: nil) { [weak self] result in
            defer { dispatchGroup.leave() }
            guard let self = self else { return }

            switch result {
            case .success(let availableInterests):
                let allSelected = self.selectedDomains + self.selectedInterests
                let allSelectedLowercased = allSelected.map { $0.lowercased() }
                
                // Find matching APIInterest objects
                let matches = availableInterests.filter { interest in
                    allSelectedLowercased.contains(interest.name.lowercased())
                }
                
                for match in matches {
                    dispatchGroup.enter()
                    // Uses the safe, native APIService.addInterest
                    api.addInterest(interestId: match.id, token: token) { saveResult in
                        switch saveResult {
                        case .success:
                            print("✅ Saved interest '\(match.name)' to DB")
                        case .failure(let error):
                            print("❌ Failed saving interest '\(match.name)': \(error)")
                        }
                        dispatchGroup.leave()
                    }
                }
                
            case .failure(let error):
                print("❌ Failed to fetch available interests: \(error)")
            }
        }

        // 3) Mark onboarding locally and navigate to Home once everything is synced
        dispatchGroup.notify(queue: .main) {
            
            // Note: If you add an /onboarding-complete route to profile.route.ts in 
            // the future, you can fire that API call right here!
            
            UserDefaults.standard.set(true, forKey: "hasOnboarding")
            print("🏁 All onboarding parameters synced! Navigating to Home.")
            
            self.navigateToHome()
        }
    }


    func navigateToHome() {
        let storyboard = UIStoryboard(name: "HomeMain", bundle: nil)
        if let homeVC = storyboard.instantiateInitialViewController() {
            // Set as root so user can't swipe back
            if let window = self.view.window {
                window.rootViewController = homeVC
                UIView.transition(with: window, duration: 0.3,
                                  options: .transitionCrossDissolve,
                                  animations: nil)
            }
        }
    }
}

